"""Serve the built workbench assets from the installed package.

The bundle is a build product, not source: it is generated by
``web/`` + Vite into ``web/static`` and shipped inside the wheel, so an
operator needs neither a source checkout nor Node.

Every path is resolved against the asset root with no symlink following and no
absolute or parent traversal, and the served content type comes from a closed
suffix table. A missing bundle is a clear server-start failure rather than a
404 that looks like an empty project.
"""

from __future__ import annotations

import hashlib
import os
import stat
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

STATIC_ROOT = Path(__file__).resolve().parent / "static"
MAX_ASSET_BYTES = 8_388_608
INDEX_NAME = "index.html"

_CONTENT_TYPES = {
    ".css": "text/css; charset=utf-8",
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".map": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".txt": "text/plain; charset=utf-8",
    ".webmanifest": "application/manifest+json",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
}
_FALLBACK_TYPE = "application/octet-stream"


class AssetError(Exception):
    """One static-asset fault with a closed code and no host path in the text."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


@dataclass(frozen=True)
class Asset:
    """One resolved asset, safe to write to a response."""

    body: bytes
    content_type: str
    etag: str
    immutable: bool


def content_type_for(name: str) -> str:
    suffix = Path(name).suffix.lower()
    return _CONTENT_TYPES.get(suffix, _FALLBACK_TYPE)


def _normalized_parts(relative: str) -> list[str]:
    """Split a request path into safe, traversal-free components."""

    candidate = relative[1:] if relative.startswith("/") else relative
    if candidate in {"", "."}:
        candidate = INDEX_NAME
    if "\x00" in candidate:
        raise AssetError("asset-path-invalid", "The asset path is not valid.")
    parts = [part for part in candidate.split("/") if part not in {"", "."}]
    if not parts or any(part == ".." for part in parts):
        raise AssetError("asset-path-invalid", "The asset path is not valid.")
    return parts


def _read_regular(descriptor: int, name: str) -> Asset:
    """Read one already-opened regular file and describe it for a response."""

    details = os.fstat(descriptor)
    if not stat.S_ISREG(details.st_mode):
        raise AssetError("asset-not-a-file", "The asset is not a regular file.")
    if details.st_size > MAX_ASSET_BYTES:
        raise AssetError("asset-too-large", "The asset exceeds the serving limit.")
    chunks: list[bytes] = []
    while True:
        chunk = os.read(descriptor, 65_536)
        if not chunk:
            break
        chunks.append(chunk)
    body = b"".join(chunks)
    return Asset(
        body=body,
        content_type=content_type_for(name),
        etag=f'"{hashlib.sha256(body).hexdigest()[:32]}"',
        immutable="-" in name,
    )


def _resolve(root: Path, relative: str) -> Asset:
    """Walk ``root`` by descriptor so no path component can be a symlink."""

    parts = _normalized_parts(relative)
    directory = os.open(root, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        opened: list[int] = []
        try:
            current = directory
            for index, part in enumerate(parts):
                last = index == len(parts) - 1
                flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0)
                if not last:
                    flags |= getattr(os, "O_DIRECTORY", 0)
                if getattr(os, "O_NOFOLLOW", 0):
                    flags |= os.O_NOFOLLOW
                current = os.open(part, flags, dir_fd=current)
                opened.append(current)
                if last:
                    return _read_regular(current, part)
            raise AssetError("asset-missing", "The requested asset is not present.")
        finally:
            for descriptor in opened:
                os.close(descriptor)
    except FileNotFoundError as exc:
        raise AssetError("asset-missing", "The requested asset is not present.") from exc
    except NotADirectoryError as exc:
        raise AssetError("asset-missing", "The requested asset is not present.") from exc
    except PermissionError as exc:
        raise AssetError("asset-forbidden", "The requested asset cannot be read.") from exc
    except OSError as exc:
        # O_NOFOLLOW on a symlink raises ELOOP, which is neither a missing file
        # nor a permission fault. It must still be a closed, non-leaking error
        # rather than an unhandled OSError that becomes a 500.
        raise AssetError("asset-path-invalid", "The asset path is not valid.") from exc
    finally:
        os.close(directory)


@lru_cache(maxsize=1)
def static_root() -> Path:
    """The installed asset root, verified once per process."""

    if not STATIC_ROOT.is_dir():
        raise AssetError(
            "assets-missing",
            "The workbench bundle is not installed. Build it in web/ (npm ci, npm run build).",
        )
    return STATIC_ROOT


def load(relative: str) -> Asset:
    """Resolve and read one asset by request path."""

    return _resolve(static_root(), relative)


def clear_cache() -> None:
    """Drop the verified root. Used by tests that install assets temporarily."""

    static_root.cache_clear()


def index_asset() -> Asset:
    return load(INDEX_NAME)
