"""Generate the browser's TypeScript types from the local API contracts.

The wire contract is owned by ``llm_research_os.web.contracts``. This renders a
deterministic ``web/src/generated/local-api.ts`` so the client cannot drift from
the server, and ``tests/test_web_contracts.py`` fails when the committed file no
longer matches.

The mapping is intentionally narrow. Only the shapes the workbench actually
consumes are emitted, and anything the generator cannot represent faithfully
becomes ``unknown`` rather than a convenient lie.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from llm_research_os.web.contracts import (  # noqa: E402
    CONTRACT_MODELS,
    LOCAL_API_CONTRACT_VERSION,
    LOCAL_API_VERSION,
)

OUTPUT = ROOT / "web" / "src" / "generated" / "local-api.ts"

_HEADER = f"""// Generated by scripts/generate_web_types.py from
// llm_research_os.web.contracts. Do not edit by hand.
//
// Run `uv run python scripts/generate_web_types.py` after changing a contract.
// tests/test_web_contracts.py fails when this file drifts from the models.

export const API_VERSION = {json.dumps(LOCAL_API_VERSION)};
export const API_PREFIX = "/api/{LOCAL_API_CONTRACT_VERSION}";
export const CONTRACT_VERSION = {json.dumps(LOCAL_API_CONTRACT_VERSION)};
"""


def _ts_type(schema: dict[str, Any]) -> str:
    """Render one JSON Schema node as a TypeScript type."""

    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_ts_type(option) for option in schema["anyOf"])
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    if kind == "integer" or kind == "number":
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"ReadonlyArray<{_ts_type(schema.get('items', {}))}>"
    if kind == "object":
        properties = schema.get("properties")
        if not properties:
            return "Readonly<Record<string, unknown>>"
        required = set(schema.get("required", ()))
        lines = []
        for name, sub in properties.items():
            optional = "" if name in required else "?"
            lines.append(f"  readonly {name}{optional}: {_ts_type(sub)};")
        return "{\n" + "\n".join(lines) + "\n}"
    return "unknown"


def _interface(name: str, model: type[Any], emitted: set[str]) -> str:
    if name in emitted:
        return ""
    emitted.add(name)
    schema = model.model_json_schema(
        by_alias=True, mode="serialization", ref_template="#/$defs/{model}"
    )
    definitions = schema.get("$defs", {})
    lines = [f"export interface {name} {{"]
    for field, sub in schema.get("properties", {}).items():
        if sub.get("type") == "null":
            continue
        marker = "" if field in schema.get("required", ()) else "?"
        lines.append(f"  readonly {field}{marker}: {_ts_type(sub)};")
    lines.append("}")
    body = "\n".join(lines)

    referenced = sorted(
        key
        for key, sub in definitions.items()
        if key != name and f"#/$defs/{key}" in json.dumps(schema.get("properties", {}))
    )
    blocks = [body]
    for key in referenced:
        nested = _interface(key, _model_for(key, model, definitions), emitted)
        if nested:
            blocks.append(nested)
    return "\n\n".join(blocks)


def _model_for(name: str, owner: type[Any], definitions: dict[str, Any]) -> type[Any]:
    for candidate in _all_models():
        if candidate.__name__ == name:
            return candidate
    raise KeyError(f"no Python model backs the contract definition {name} in {owner.__name__}")


def _all_models() -> list[type[Any]]:
    seen: dict[str, type[Any]] = {}
    for model in CONTRACT_MODELS.values():
        for nested in _nested(model):
            seen.setdefault(nested.__name__, nested)
    return list(seen.values())


def _nested(model: type[Any]) -> list[type[Any]]:
    from pydantic import BaseModel

    found: list[type[Any]] = [model]
    for field in model.model_fields.values():
        annotation = field.annotation
        for candidate in _annotations(annotation):
            if isinstance(candidate, type) and issubclass(candidate, BaseModel):
                found.extend(_nested(candidate))
    return found


def _annotations(annotation: Any) -> list[Any]:
    from typing import get_args, get_origin

    if annotation is None:
        return []
    origin = get_origin(annotation)
    if origin is None:
        return [annotation]
    return [arg for arg in get_args(annotation) if arg is not type(None)]


def render() -> str:
    blocks = [_HEADER]
    emitted: set[str] = set()
    for name, model in CONTRACT_MODELS.items():
        block = _interface(name, model, emitted)
        if block:
            blocks.append(block)
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
